// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: framework/actor/pb/remote.proto

package actorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteMessageKind int32

const (
	RemoteMessageKind_REMOTE_MESSAGE_KIND_UNSPECIFIED RemoteMessageKind = 0
	RemoteMessageKind_ASK_RESPONSE                    RemoteMessageKind = 2
	RemoteMessageKind_ASK_ERROR                       RemoteMessageKind = 3
)

// Enum value maps for RemoteMessageKind.
var (
	RemoteMessageKind_name = map[int32]string{
		0: "REMOTE_MESSAGE_KIND_UNSPECIFIED",
		2: "ASK_RESPONSE",
		3: "ASK_ERROR",
	}
	RemoteMessageKind_value = map[string]int32{
		"REMOTE_MESSAGE_KIND_UNSPECIFIED": 0,
		"ASK_RESPONSE":                    2,
		"ASK_ERROR":                       3,
	}
)

func (x RemoteMessageKind) Enum() *RemoteMessageKind {
	p := new(RemoteMessageKind)
	*p = x
	return p
}

func (x RemoteMessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteMessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_framework_actor_pb_remote_proto_enumTypes[0].Descriptor()
}

func (RemoteMessageKind) Type() protoreflect.EnumType {
	return &file_framework_actor_pb_remote_proto_enumTypes[0]
}

func (x RemoteMessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteMessageKind.Descriptor instead.
func (RemoteMessageKind) EnumDescriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{0}
}

type PID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       uint64                 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorName     string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_framework_actor_pb_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_framework_actor_pb_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{0}
}

func (x *PID) GetActorId() uint64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *PID) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *PID) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RequestRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRef) Reset() {
	*x = RequestRef{}
	mi := &file_framework_actor_pb_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRef) ProtoMessage() {}

func (x *RequestRef) ProtoReflect() protoreflect.Message {
	mi := &file_framework_actor_pb_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRef.ProtoReflect.Descriptor instead.
func (*RequestRef) Descriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{1}
}

func (x *RequestRef) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RequestRef) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type RemoteActorCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePid     *PID                   `protobuf:"bytes,1,opt,name=source_pid,json=sourcePid,proto3" json:"source_pid,omitempty"`
	TargetPid     *PID                   `protobuf:"bytes,2,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteActorCommon) Reset() {
	*x = RemoteActorCommon{}
	mi := &file_framework_actor_pb_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteActorCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteActorCommon) ProtoMessage() {}

func (x *RemoteActorCommon) ProtoReflect() protoreflect.Message {
	mi := &file_framework_actor_pb_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteActorCommon.ProtoReflect.Descriptor instead.
func (*RemoteActorCommon) Descriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteActorCommon) GetSourcePid() *PID {
	if x != nil {
		return x.SourcePid
	}
	return nil
}

func (x *RemoteActorCommon) GetTargetPid() *PID {
	if x != nil {
		return x.TargetPid
	}
	return nil
}

func (x *RemoteActorCommon) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type RemoteActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageName   string                 `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Request       *RequestRef            `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteActorRequest) Reset() {
	*x = RemoteActorRequest{}
	mi := &file_framework_actor_pb_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteActorRequest) ProtoMessage() {}

func (x *RemoteActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_framework_actor_pb_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteActorRequest.ProtoReflect.Descriptor instead.
func (*RemoteActorRequest) Descriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteActorRequest) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *RemoteActorRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RemoteActorRequest) GetRequest() *RequestRef {
	if x != nil {
		return x.Request
	}
	return nil
}

type RemoteActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          RemoteMessageKind      `protobuf:"varint,1,opt,name=kind,proto3,enum=actor.RemoteMessageKind" json:"kind,omitempty"`
	Request       *RequestRef            `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	MessageName   string                 `protobuf:"bytes,3,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     uint32                 `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteActorResponse) Reset() {
	*x = RemoteActorResponse{}
	mi := &file_framework_actor_pb_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteActorResponse) ProtoMessage() {}

func (x *RemoteActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_framework_actor_pb_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteActorResponse.ProtoReflect.Descriptor instead.
func (*RemoteActorResponse) Descriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{4}
}

func (x *RemoteActorResponse) GetKind() RemoteMessageKind {
	if x != nil {
		return x.Kind
	}
	return RemoteMessageKind_REMOTE_MESSAGE_KIND_UNSPECIFIED
}

func (x *RemoteActorResponse) GetRequest() *RequestRef {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RemoteActorResponse) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *RemoteActorResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RemoteActorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RemoteActorResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type RemoteActorMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Common *RemoteActorCommon     `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*RemoteActorMessage_Request
	//	*RemoteActorMessage_Response
	Body          isRemoteActorMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteActorMessage) Reset() {
	*x = RemoteActorMessage{}
	mi := &file_framework_actor_pb_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteActorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteActorMessage) ProtoMessage() {}

func (x *RemoteActorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_framework_actor_pb_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteActorMessage.ProtoReflect.Descriptor instead.
func (*RemoteActorMessage) Descriptor() ([]byte, []int) {
	return file_framework_actor_pb_remote_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteActorMessage) GetCommon() *RemoteActorCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *RemoteActorMessage) GetBody() isRemoteActorMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RemoteActorMessage) GetRequest() *RemoteActorRequest {
	if x != nil {
		if x, ok := x.Body.(*RemoteActorMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *RemoteActorMessage) GetResponse() *RemoteActorResponse {
	if x != nil {
		if x, ok := x.Body.(*RemoteActorMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isRemoteActorMessage_Body interface {
	isRemoteActorMessage_Body()
}

type RemoteActorMessage_Request struct {
	Request *RemoteActorRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type RemoteActorMessage_Response struct {
	Response *RemoteActorResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*RemoteActorMessage_Request) isRemoteActorMessage_Body() {}

func (*RemoteActorMessage_Response) isRemoteActorMessage_Body() {}

var File_framework_actor_pb_remote_proto protoreflect.FileDescriptor

const file_framework_actor_pb_remote_proto_rawDesc = "" +
	"\n" +
	"\x1fframework/actor/pb/remote.proto\x12\x05actor\"X\n" +
	"\x03PID\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x04R\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"D\n" +
	"\n" +
	"RequestRef\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\"\x8f\x01\n" +
	"\x11RemoteActorCommon\x12)\n" +
	"\n" +
	"source_pid\x18\x01 \x01(\v2\n" +
	".actor.PIDR\tsourcePid\x12)\n" +
	"\n" +
	"target_pid\x18\x02 \x01(\v2\n" +
	".actor.PIDR\ttargetPid\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\"~\n" +
	"\x12RemoteActorRequest\x12!\n" +
	"\fmessage_name\x18\x01 \x01(\tR\vmessageName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12+\n" +
	"\arequest\x18\x03 \x01(\v2\x11.actor.RequestRefR\arequest\"\xe2\x01\n" +
	"\x13RemoteActorResponse\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.actor.RemoteMessageKindR\x04kind\x12+\n" +
	"\arequest\x18\x02 \x01(\v2\x11.actor.RequestRefR\arequest\x12!\n" +
	"\fmessage_name\x18\x03 \x01(\tR\vmessageName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\rR\terrorCode\"\xbf\x01\n" +
	"\x12RemoteActorMessage\x120\n" +
	"\x06common\x18\x01 \x01(\v2\x18.actor.RemoteActorCommonR\x06common\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x19.actor.RemoteActorRequestH\x00R\arequest\x128\n" +
	"\bresponse\x18\x03 \x01(\v2\x1a.actor.RemoteActorResponseH\x00R\bresponseB\x06\n" +
	"\x04body*Y\n" +
	"\x11RemoteMessageKind\x12#\n" +
	"\x1fREMOTE_MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fASK_RESPONSE\x10\x02\x12\r\n" +
	"\tASK_ERROR\x10\x03B(Z&game-server/framework/actor/pb;actorpbb\x06proto3"

var (
	file_framework_actor_pb_remote_proto_rawDescOnce sync.Once
	file_framework_actor_pb_remote_proto_rawDescData []byte
)

func file_framework_actor_pb_remote_proto_rawDescGZIP() []byte {
	file_framework_actor_pb_remote_proto_rawDescOnce.Do(func() {
		file_framework_actor_pb_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_framework_actor_pb_remote_proto_rawDesc), len(file_framework_actor_pb_remote_proto_rawDesc)))
	})
	return file_framework_actor_pb_remote_proto_rawDescData
}

var file_framework_actor_pb_remote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_framework_actor_pb_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_framework_actor_pb_remote_proto_goTypes = []any{
	(RemoteMessageKind)(0),      // 0: actor.RemoteMessageKind
	(*PID)(nil),                 // 1: actor.PID
	(*RequestRef)(nil),          // 2: actor.RequestRef
	(*RemoteActorCommon)(nil),   // 3: actor.RemoteActorCommon
	(*RemoteActorRequest)(nil),  // 4: actor.RemoteActorRequest
	(*RemoteActorResponse)(nil), // 5: actor.RemoteActorResponse
	(*RemoteActorMessage)(nil),  // 6: actor.RemoteActorMessage
}
var file_framework_actor_pb_remote_proto_depIdxs = []int32{
	1, // 0: actor.RemoteActorCommon.source_pid:type_name -> actor.PID
	1, // 1: actor.RemoteActorCommon.target_pid:type_name -> actor.PID
	2, // 2: actor.RemoteActorRequest.request:type_name -> actor.RequestRef
	0, // 3: actor.RemoteActorResponse.kind:type_name -> actor.RemoteMessageKind
	2, // 4: actor.RemoteActorResponse.request:type_name -> actor.RequestRef
	3, // 5: actor.RemoteActorMessage.common:type_name -> actor.RemoteActorCommon
	4, // 6: actor.RemoteActorMessage.request:type_name -> actor.RemoteActorRequest
	5, // 7: actor.RemoteActorMessage.response:type_name -> actor.RemoteActorResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_framework_actor_pb_remote_proto_init() }
func file_framework_actor_pb_remote_proto_init() {
	if File_framework_actor_pb_remote_proto != nil {
		return
	}
	file_framework_actor_pb_remote_proto_msgTypes[5].OneofWrappers = []any{
		(*RemoteActorMessage_Request)(nil),
		(*RemoteActorMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_framework_actor_pb_remote_proto_rawDesc), len(file_framework_actor_pb_remote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_framework_actor_pb_remote_proto_goTypes,
		DependencyIndexes: file_framework_actor_pb_remote_proto_depIdxs,
		EnumInfos:         file_framework_actor_pb_remote_proto_enumTypes,
		MessageInfos:      file_framework_actor_pb_remote_proto_msgTypes,
	}.Build()
	File_framework_actor_pb_remote_proto = out.File
	file_framework_actor_pb_remote_proto_goTypes = nil
	file_framework_actor_pb_remote_proto_depIdxs = nil
}
