// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: framework/logicalactor/pb/logical.proto

package logicalactorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorID) Reset() {
	*x = ActorID{}
	mi := &file_framework_logicalactor_pb_logical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorID) ProtoMessage() {}

func (x *ActorID) ProtoReflect() protoreflect.Message {
	mi := &file_framework_logicalactor_pb_logical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorID.ProtoReflect.Descriptor instead.
func (*ActorID) Descriptor() ([]byte, []int) {
	return file_framework_logicalactor_pb_logical_proto_rawDescGZIP(), []int{0}
}

func (x *ActorID) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ActorID) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_framework_logicalactor_pb_logical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_framework_logicalactor_pb_logical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_framework_logicalactor_pb_logical_proto_rawDescGZIP(), []int{1}
}

func (x *Owner) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Owner) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Owner) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       *ActorID               `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Message       *anypb.Any             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ForwardCount  uint32                 `protobuf:"varint,4,opt,name=forward_count,json=forwardCount,proto3" json:"forward_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_framework_logicalactor_pb_logical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_framework_logicalactor_pb_logical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_framework_logicalactor_pb_logical_proto_rawDescGZIP(), []int{2}
}

func (x *RouteRequest) GetActorId() *ActorID {
	if x != nil {
		return x.ActorId
	}
	return nil
}

func (x *RouteRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *RouteRequest) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RouteRequest) GetForwardCount() uint32 {
	if x != nil {
		return x.ForwardCount
	}
	return 0
}

var File_framework_logicalactor_pb_logical_proto protoreflect.FileDescriptor

const file_framework_logicalactor_pb_logical_proto_rawDesc = "" +
	"\n" +
	"'framework/logicalactor/pb/logical.proto\x12\flogicalactor\x1a\x19google/protobuf/any.proto\"/\n" +
	"\aActorID\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"W\n" +
	"\x05Owner\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\"\xc0\x01\n" +
	"\fRouteRequest\x120\n" +
	"\bactor_id\x18\x01 \x01(\v2\x15.logicalactor.ActorIDR\aactorId\x12)\n" +
	"\x05owner\x18\x02 \x01(\v2\x13.logicalactor.OwnerR\x05owner\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\amessage\x12#\n" +
	"\rforward_count\x18\x04 \x01(\rR\fforwardCountB6Z4game-server/framework/logicalactor/pb;logicalactorpbb\x06proto3"

var (
	file_framework_logicalactor_pb_logical_proto_rawDescOnce sync.Once
	file_framework_logicalactor_pb_logical_proto_rawDescData []byte
)

func file_framework_logicalactor_pb_logical_proto_rawDescGZIP() []byte {
	file_framework_logicalactor_pb_logical_proto_rawDescOnce.Do(func() {
		file_framework_logicalactor_pb_logical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_framework_logicalactor_pb_logical_proto_rawDesc), len(file_framework_logicalactor_pb_logical_proto_rawDesc)))
	})
	return file_framework_logicalactor_pb_logical_proto_rawDescData
}

var file_framework_logicalactor_pb_logical_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_framework_logicalactor_pb_logical_proto_goTypes = []any{
	(*ActorID)(nil),      // 0: logicalactor.ActorID
	(*Owner)(nil),        // 1: logicalactor.Owner
	(*RouteRequest)(nil), // 2: logicalactor.RouteRequest
	(*anypb.Any)(nil),    // 3: google.protobuf.Any
}
var file_framework_logicalactor_pb_logical_proto_depIdxs = []int32{
	0, // 0: logicalactor.RouteRequest.actor_id:type_name -> logicalactor.ActorID
	1, // 1: logicalactor.RouteRequest.owner:type_name -> logicalactor.Owner
	3, // 2: logicalactor.RouteRequest.message:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_framework_logicalactor_pb_logical_proto_init() }
func file_framework_logicalactor_pb_logical_proto_init() {
	if File_framework_logicalactor_pb_logical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_framework_logicalactor_pb_logical_proto_rawDesc), len(file_framework_logicalactor_pb_logical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_framework_logicalactor_pb_logical_proto_goTypes,
		DependencyIndexes: file_framework_logicalactor_pb_logical_proto_depIdxs,
		MessageInfos:      file_framework_logicalactor_pb_logical_proto_msgTypes,
	}.Build()
	File_framework_logicalactor_pb_logical_proto = out.File
	file_framework_logicalactor_pb_logical_proto_goTypes = nil
	file_framework_logicalactor_pb_logical_proto_depIdxs = nil
}
